### ISSUE TITLE
I'd like to help you developing this project

### ISSUE THREAD

**Issue by LazyTurtle** [Plaristote/fallout-equestria-reloaded#2]
I'd like to develop this project and maybe build something interesting, but there are no guidelines for contributions.
I would have also liked to contact you via email but I couldn't find any.

**Comment by Plaristote** [comment]
Hi ! We have a discord account, does that sound good ?
https://discord.gg/89MmrkrA
It's a temporary link, expires in 7 days. I'm afraid posting permalinks would come with the necessity of moderating the room, but otherwise you can reach me by mail through the recruitment form at https://falloutequestriarpg.wordpress.com !
